friend_info_西柚-北京阿里: {Name: 西柚-北京阿里, content: " \"圣诞老人在路上～～\"\n  ", link: 没有获取到链接,
  linkText: ' ', picturePath: ' '}
friend_info_杨佳天: {Name: 杨佳天, content: 用户没有发表正文信息, link: 没有获取到链接, linkText: ' ', picturePath: ' '}
friend_info_西柚-北京阿里: {Name: 西柚-北京阿里, content: " \"圣诞老人在路上～～\"\n  ", link: ' ', linkText: ' ',
  picturePath: ' '}
friend_info_杨佳天: {Name: 杨佳天, content: " \"圣诞\U0001F384收到最喜欢的礼物哈哈哈哈\"\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_清华计算机学长: {Name: 清华计算机学长, content: " \"小马智行Pony.AI获得国家交通部大赛特等奖，从全国近1500个项目中脱颖而出，Pony.AI的L4自动驾驶全栈式技术解决方案获得国家层面的巨大支持！\"\
    \n  ", link: ' ', linkText: ' ', picturePath: ' '}
friend_info_陈佳敏: {Name: 陈佳敏, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
"friend_info_\U0001F434": {Name: "\U0001F434", content: 用户没有发表正文信息, link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_顾向彦: {Name: 顾向彦, content: " \"差不多靠岸啦，拖轮来怼我们了\U0001F602\"\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_Aaron: {Name: Aaron, content: " \"谁还不是个睫毛精咋的\U0001F937‍♂️\"\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_Aaron: {Name: Aaron, content: " \"谁还不是个睫毛精咋的\U0001F937‍♂️\"\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_孟诚: {Name: 孟诚, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_黄晓梅老师: {Name: 黄晓梅老师, content: " \"麻烦大家投票啦七号作品七号作品[抱拳][抱拳][抱拳]\"\n  ",
  link: ' ', linkText: ' ', picturePath: ' '}
friend_info_周佳美: {Name: 周佳美, content: " \"忍不住来一张摆拍[捂脸]\"\n  ", link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_杨紫博: {Name: 杨紫博, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_王永飞: {Name: 王永飞, content: " \"心中没有了念想，大概便是阴天吧\"\n  ", link: ' ', linkText: ' ',
  picturePath: ' '}
friend_info_唐维-支付宝: {Name: 唐维-支付宝, content: " \"从一个人人都羡慕的最豪华实验室，搬到了一个惨不忍睹的实验室，还被锁在外面[心碎][心碎][心碎][心碎]\"\
    \n  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_俞佳盈®: {Name: 俞佳盈®, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_俞佳盈®: {Name: 俞佳盈®, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_俞佳盈®: {Name: 俞佳盈®, content: " \"【Niagara Falls】\n  2016 from American\
    \ side\n  2018 from Canadian side\n  雷神之水 气吞山河\"\n  ", link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_吴洁-新零售-算法: {Name: 吴洁-新零售-算法, content: " \"刚更新了微信 奇怪为什么有些人的头像右上角有一个小蓝圈呀？\n\
    \  \n  有胖友解释一下嘛…\"\n  ", link: ' ', linkText: ' ', picturePath: ' '}
friend_info_大黑楼的外卖店: {Name: 大黑楼的外卖店, content: " \"日照绿茶引用传统制作工艺，不添加任何化学物质。山东省日照市特产，中国国家地理标志产品。日照是世界茶学家公认的三大海绿茶城市之一（另两个分别为日本静冈和韩国宝城）。日照绿茶具有汤色黄绿明亮、栗香浓郁、回味甘醇、叶片厚、香气高、耐冲泡等独特优良品质，被誉为“中国绿茶新贵”。\"\
    \n  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_大黑楼的外卖店: {Name: 大黑楼的外卖店, content: " \"BOSS Wsllet 理财购物一条龙\n  霸屏天下 体现到钱包不收取手续费！！！\"\
    \n  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_大黑楼的外卖店: {Name: 大黑楼的外卖店, content: " \"BOSS Wsllet 理财购物一条龙\n  霸屏天下 体现到钱包不收取手续费！！！\"\
    \n  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_万梓潇-蚂蚁设计师-美国: {Name: 万梓潇-蚂蚁设计师-美国, content: " \"有点喜欢优步的小动效[太阳]\"\n  ",
  link: ' ', linkText: ' ', picturePath: ' '}
friend_info_吴汀阳: {Name: 吴汀阳, content: " \"每年的12月24日晚上，我们都会等待一个红帽子白胡子老头。\"\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_小洁: {Name: 小洁, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_吴彦桦: {Name: 吴彦桦, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_蔡奇-国际部: {Name: 蔡奇-国际部, content: " Broadcast completed: result=0\n  ",
  link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_曾晓南: {Name: 曾晓南, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_黄松松: {Name: 黄松松, content: " \"接到一个电话让我很感动\n  \n  五点在群里发了条消息讲近视，五点半就接到家长电话，和我沟通孩子的情况\n\
    \  \n  对孩子如此上心，真的不容易\n  \n  然后想到上星期没给家里打电话\U0001F602\"\n  ", link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_堡垒: {Name: 堡垒, content: " \"你们要的红帽子，白胡子老头\"\n  ", link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_吴彦桦: {Name: 吴彦桦, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_黄磊-北大: {Name: 黄磊-北大, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_八戒: {Name: 八戒, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_李威: {Name: 李威, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_孟诚: {Name: 孟诚, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_罗静: {Name: 罗静, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_周梅芳-室友: {Name: 周梅芳-室友, content: 用户没有发表正文信息, link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_吴彦桦: {Name: 吴彦桦, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_张泽-算法-蚂蚁: {Name: 张泽-算法-蚂蚁, content: 用户没有发表正文信息, link: ' ', linkText: ' ',
  picturePath: ' '}
friend_info_Ivan Huang: {Name: Ivan Huang, content: " Broadcast completed: result=0\n\
    \  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_Ivan Huang: {Name: Ivan Huang, content: " Broadcast completed: result=0\n\
    \  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_刘猛猛: {Name: 刘猛猛, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_千年陈醋: {Name: 千年陈醋, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_大黑楼的外卖店: {Name: 大黑楼的外卖店, content: " Broadcast completed: result=0\n  ",
  link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_大黑楼的外卖店: {Name: 大黑楼的外卖店, content: " Broadcast completed: result=0\n  ",
  link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_黄怡: {Name: 黄怡, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_头像一般啦~: {Name: 头像一般啦~, content: " Broadcast completed: result=0\n  ",
  link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_周梁: {Name: 周梁, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_吴汀阳: {Name: 吴汀阳, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_二艿艿: {Name: 二艿艿, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_二艿艿: {Name: 二艿艿, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_林焱-12级老乡: {Name: 林焱-12级老乡, content: 用户没有发表正文信息, link: ' ', linkText: ' ',
  picturePath: ' '}
friend_info_林焱-12级老乡: {Name: 林焱-12级老乡, content: " Broadcast completed: result=0\n\
    \  ", link: ' ', linkText: ' ', picturePath: ' '}
friend_info_张晶-党支部书记: {Name: 张晶-党支部书记, content: 用户没有发表正文信息, link: ' ', linkText: ' ',
  picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_不胖到135不改名: {Name: 不胖到135不改名, content: " Broadcast completed: result=0\n\
    \  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_钭怀啸-支付宝-nlp: {Name: 钭怀啸-支付宝-nlp, content: " Broadcast completed: result=0\n\
    \  ", link: ' ', linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
friend_info_董兆晨: {Name: 董兆晨, content: 用户没有发表正文信息, link: ' ', linkText: ' ', picturePath: ' '}
friend_info_腾主席: {Name: 腾主席, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: ' '}
friend_info_俞佳盈®: {Name: 俞佳盈®, content: " Broadcast completed: result=0\n  ", link: ' ',
  linkText: ' ', picturePath: /Users/kang/Documents/github/Appuim_py/screenshots/WeiXin}
